version: '3'

services:
  telehooks:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8443:8443"
    depends_on:
      - mq
    command: python3 __main__.py

  mq:
    restart: always
    image: rabbitmq:3.13.6
    networks:
      - default
      - telehooks_mq

volumes:
  postgres_data: { }

networks:
  telehooks_mq:
    external: true
